/***********************************************************************/
/*                                                                     */
/*      PROJECT NAME :  sketch                                         */
/*      FILE         :  interrupt_handlers.h                           */
/*      DESCRIPTION  :  Interrupt Handler Declarations                 */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  RX63N                                          */
/*                                                                     */
/*      This file is generated by e2studio.                            */
/*                                                                     */
/***********************************************************************/

#ifndef USER_INTERRUPT_H
#define USER_INTERRUPT_H

#define __ATTRIBUTE_INTERRUPT __attribute__ ((interrupt))

#include "interrupt_handlers.h"

#endif/*USER_INTERRUPT_H*/
